# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
  
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_HUB_NAME }}
        password: ${{ secrets.DOCKER_HUB_PWD }}
        logout: true
        
    - name: Build && Push Image
      run: |
        docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/liangzijin/gitops-demo:${{ github.sha }}
        docker push registry.cn-hangzhou.aliyuncs.com/liangzijin/gitops-demo:${{ github.sha }}

    - name: Trigger CI
      uses: InformaticsMatters/trigger-ci-action@1.0.1
      with:
        ci-owner: liangzijin
        ci-repository: gitops-demo-kustomize
        ci-ref: refs/heads/main
        ci-user: liangzijin
        ci-user-token: ${{ secrets.CI_TOKEN }}
        ci-name: CI
        ci-inputs: >-
            image=registry.cn-hangzhou.aliyuncs.com/liangzijin/gitops-demo
            sha-tag=${{ github.sha }}